services:
  app:
    build: .
    container_name: ${PROJECT_NAME}_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/app
    environment:
      APP_ENV: 
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=${DB_VERSION}&charset=utf8mb4
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
    depends_on:
      - database
      - redis
    networks:
      - connecting_network

  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./snippets:/etc/nginx/snippets
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - connecting_network

  database:
    image: mariadb:11.4.5
    container_name: ${PROJECT_NAME}_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: ${PROJECT_NAME}_db
      MYSQL_USER: ${PROJECT_NAME}_user
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "3806:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/db/data:/var/lib/mysql
    networks:
      - connecting_network

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}_redis
    restart: unless-stopped
    networks:
      - connecting_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8880:80"
    networks:
      - connecting_network

networks:
  connecting_network:
    driver: bridge

volumes:
  mariadb_data:
