CREATE DATABASE IF NOT EXISTS ${DB_NAME};
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
CREATE USER IF NOT EXISTS '${DB_NAME}'@'%' IDENTIFIED BY '7376174a36b17908fd63b72ce2d4bef7';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_NAME}'@'%';
FLUSH PRIVILEGES;

-- CREATE DATABASE IF NOT EXISTS brokerdb_one;
-- CREATE USER IF NOT EXISTS 'brokerdb_one'@'%' IDENTIFIED BY '5db3d025c8c303e47a897be0524c047d';
-- GRANT ALL PRIVILEGES ON brokerdb_one.* TO 'brokerdb_one'@'%';
-- FLUSH PRIVILEGES;